import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Verify Email - TikTokClone',
  description: 'Generated by create next app'
}

export default function VerifyEmailLayout({ children }: { children: React.ReactNode }) {
  return <section>VerifyEmailLayout {children}</section>
}
